name: 'dbt_meetup'
version: '1.0.0'

profile: 'dbt_meetup'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "dev.duckdb"

models:
  dbt_meetup:
    prata:
      +materialized: view
      +schema: prata
    ouro:
      +materialized: table
      +schema: ouro

seeds:
  dbt_meetup:
    +schema: bronze
